output_dir: ${SCRATCH}/heptrkx/results/agnn_000

trainer:
    name: gnn_sparse
    real_weight: 6.25  # 0.5 / 0.08
    fake_weight: 0.54  # 0.5 / 0.92

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_000
    n_train: 32768
    n_valid: 4096
    batch_size: 1
    n_workers: 4

model:
    name: agnn
    input_dim: 3
    hidden_dim: 64
    n_iters: 8
    loss_func: binary_cross_entropy_with_logits
    optimizer: Adam
    learning_rate: 0.001

training:
    n_epochs: 64
