output_dir: ${SCRATCH}/heptrkx/results/agnn_001

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_000
    n_train: 32768
    n_valid: 4096
    real_weight: 6.25  # 0.5 / 0.08
    batch_size: 1
    n_workers: 4

model:
    name: agnn
    input_dim: 3
    hidden_dim: 64
    n_iters: 8
    loss_func: binary_cross_entropy_with_logits
    optimizer:
        name: SGD
        momentum: 0.9
        learning_rate: 0.001
        lr_scaling: linear
        lr_warmup_epochs: 5
        lr_decay_schedule:
            - {start_epoch: 16, end_epoch: 32, factor: 0.1}
            - {start_epoch: 32, end_epoch: 64, factor: 0.01}

training:
    n_epochs: 64
