output_dir: ${SCRATCH}/heptrkx/results/agnn_pbt_000

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_000
    n_train: 1024 #57344
    n_valid: 1024
    real_weight: 5 #6.25  # 0.5 / 0.08
    batch_size: 4
    n_workers: 1

model:
    name: agnn
    input_dim: 3
    hidden_dim: 32
    n_graph_iters: 4
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    learning_rate: 0.001

training:
    n_total_epochs: 64
