output_dir: ${SCRATCH}/heptrkx/results/mpnn_med_001

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_med_002
    n_train: 16384
    n_valid: 2048
    real_weight: 2.5   # 0.5 / 0.2
    batch_size: 1
    n_workers: 4

model:
    name: mpnn
    input_dim: 3
    hidden_node_dim: 64
    hidden_edge_dim: 64
    n_graph_iters: 4
    loss_func: binary_cross_entropy_with_logits
    optimizer: Adam
    learning_rate: 0.001

training:
    n_epochs: 32
