output_dir: ${SCRATCH}/heptrkx/results/resmpnn_001

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_000
    n_train: 32768
    n_valid: 4096
    real_weight: 6.25  # 0.5 / 0.08
    batch_size: 1
    n_workers: 4

model:
    name: resmpnn
    input_dim: 3
    hidden_node_dim: 64
    hidden_edge_dim: 64
    #layer_norm: true
    n_graph_iters: 8
    loss_func: binary_cross_entropy_with_logits
    optimizer: Adam
    learning_rate: 0.001

training:
    n_epochs: 64
