output_dir: ${SCRATCH}/heptrkx/results/gnnsegclf_med_011

trainer:
    name: gnn
    real_weight: 2.5   # 0.5 / 0.2
    fake_weight: 0.625 # 0.5 / 0.8

data:
    name: hitgraphs
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_med_002
    n_train: 16384
    n_valid: 2048
    batch_size: 1
    n_workers: 4

model:
    name: 'agnn_original'
    input_dim: 3
    hidden_dim: 64
    n_iters: 4
    loss_func: 'binary_cross_entropy_with_logits'
    optimizer: 'Adam'
    learning_rate: 0.001
    lr_scaling: 'linear'
    lr_warmup_epochs: 2

training:
    n_epochs: 64
