output_dir: ${SCRATCH}/heptrkx/results/gnnsegclf_small_002

trainer:
    name: gnn

data:
    name: hitgraphs
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_small_000
    n_train: 16384
    n_valid: 2048
    batch_size: 1
    n_workers: 6

model:
    name: 'agnn_original'
    input_dim: 3
    hidden_dim: 64
    n_iters: 4
    loss_func: 'binary_cross_entropy_with_logits'
    optimizer: 'Adam'
    learning_rate: 0.001
    lr_scaling: 'linear'

training:
    n_epochs: 32
